title: Sepochi Co
baseURL: /
params:
  palette: cyan
  snipcart_api_key: NDk0ZmZlNjktMGM5NC00NjEyLTkxNDEtYTY2MDg5ZTA0NzRlNjM3MDAzNTU0MTQxNDkyMjM1
  favicon: /images/beige-celery.svg
  logo_light: /images/violet-squid.png
  logo_dark: /images/caring-tortoise.png
  hamburger_background_image: /images/default-monochrome.svg
  bg_image_primary: /images/header.jpg
  bg_image_primary_opacity: 60
  bg_image_secondary: /images/default-monochrome.svg
  bg_image_product: /images/default-monochrome.svg
  main_menu:
    - type: action
      title: Store
      url: /store
      style: link
    - type: action
      title: About
      url: /about
      style: link
    - type: action
      title: FAQ
      url: /faq
      style: link
  footer_text: Copyright 2021 Sepochi Co. All rights reserved.
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
